// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_Home_Page.h"
#include "ui_Live_Data.h"
#include "ui_Historic_Data.h"
#include "ui_Live_Data_Overview.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_509871886);   // assets/aaemv-owtp6.png
LV_IMG_DECLARE( ui_img_1742220310);   // assets/aojam-oila1.png
LV_IMG_DECLARE( ui_img_690597470);   // assets/aui6n-5rbzb.png
LV_IMG_DECLARE( ui_img_livedataiconsmall_png);   // assets/LiveDataIconSmall.png
LV_IMG_DECLARE( ui_img_1401728645);   // assets/x1-8.png
LV_IMG_DECLARE( ui_img_1953993994);   // assets/y1-8.png
LV_IMG_DECLARE( ui_img_historicdataiconsmall_png);   // assets/HistoricDataIconSmall.png
LV_IMG_DECLARE( ui_img_896003668);   // assets/x25-32.png
LV_IMG_DECLARE( ui_img_1485633761);   // assets/y17-24.png
LV_IMG_DECLARE( ui_img_1845464892);   // assets/x17-24.png
LV_IMG_DECLARE( ui_img_988524616);   // assets/x9-16.png
LV_IMG_DECLARE( ui_img_1671086701);   // assets/y9-16.png

// FONTS
LV_FONT_DECLARE( ui_font_Futura_Bold_56);
LV_FONT_DECLARE( ui_font_Futura_Book);
LV_FONT_DECLARE( ui_font_Futura_Book_26);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
