// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Home_Page = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Title = NULL;lv_obj_t *ui_LiveData = NULL;lv_obj_t *ui_HistoricData = NULL;lv_obj_t *ui_LiveDataLabel = NULL;lv_obj_t *ui_HistoricDataLabel = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Image7 = NULL;
// event funtions
void ui_event_LiveData( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data_Overview, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_Overview_screen_init);
}
}

void ui_event_HistoricData( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Historic_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Historic_Data_screen_init);
}
}

// build funtions

void ui_Home_Page_screen_init(void)
{
ui_Home_Page = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home_Page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Home_Page, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Home_Page, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
ui_object_set_themeable_style_property(ui_Home_Page, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
ui_object_set_themeable_style_property(ui_Home_Page, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
lv_obj_set_style_border_width(ui_Home_Page, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Home_Page);
lv_obj_set_width( ui_Panel1, 320);
lv_obj_set_height( ui_Panel1, 420);
lv_obj_set_x( ui_Panel1, 445 );
lv_obj_set_y( ui_Panel1, 20 );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Title = lv_label_create(ui_Home_Page);
lv_obj_set_width( ui_Title, 295);
lv_obj_set_height( ui_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Title, 17 );
lv_obj_set_y( ui_Title, 20 );
lv_label_set_text(ui_Title,"Pressure Sensor Pad");
lv_obj_set_style_text_font(ui_Title, &ui_font_Futura_Bold_56, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LiveData = lv_btn_create(ui_Home_Page);
lv_obj_set_width( ui_LiveData, 140);
lv_obj_set_height( ui_LiveData, 140);
lv_obj_set_x( ui_LiveData, 535 );
lv_obj_set_y( ui_LiveData, 50 );
lv_obj_add_flag( ui_LiveData, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_LiveData, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_LiveData, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_LiveData, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
lv_obj_set_style_bg_img_src( ui_LiveData, &ui_img_509871886, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_LiveData, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_LiveData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_LiveData, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_LiveData, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_LiveData, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_LiveData, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HistoricData = lv_btn_create(ui_Home_Page);
lv_obj_set_width( ui_HistoricData, 140);
lv_obj_set_height( ui_HistoricData, 140);
lv_obj_set_x( ui_HistoricData, 535 );
lv_obj_set_y( ui_HistoricData, 260 );
lv_obj_add_flag( ui_HistoricData, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HistoricData, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_HistoricData, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_HistoricData, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
lv_obj_set_style_bg_img_src( ui_HistoricData, &ui_img_1742220310, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_HistoricData, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HistoricData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_HistoricData, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_HistoricData, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_HistoricData, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_HistoricData, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LiveDataLabel = lv_label_create(ui_Home_Page);
lv_obj_set_width( ui_LiveDataLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LiveDataLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LiveDataLabel, 575 );
lv_obj_set_y( ui_LiveDataLabel, 200 );
lv_label_set_text(ui_LiveDataLabel,"Live Data");
lv_obj_set_style_text_font(ui_LiveDataLabel, &ui_font_Futura_Book, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HistoricDataLabel = lv_label_create(ui_Home_Page);
lv_obj_set_width( ui_HistoricDataLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HistoricDataLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HistoricDataLabel, 560 );
lv_obj_set_y( ui_HistoricDataLabel, 410 );
lv_label_set_text(ui_HistoricDataLabel,"Historic Data");
lv_obj_set_style_text_font(ui_HistoricDataLabel, &ui_font_Futura_Book, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Home_Page);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 17 );
lv_obj_set_y( ui_Label5, 140 );
lv_label_set_text(ui_Label5,"Created By: Alex Ahitov");
lv_obj_set_style_text_font(ui_Label5, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image7 = lv_img_create(ui_Home_Page);
lv_img_set_src(ui_Image7, &ui_img_690597470);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image7, -3 );
lv_obj_set_y( ui_Image7, 399 );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_LiveData, ui_event_LiveData, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HistoricData, ui_event_HistoricData, LV_EVENT_ALL, NULL);

}

void ui_Home_Page_screen_destroy(void)
{
   if (ui_Home_Page) lv_obj_del(ui_Home_Page);

// NULL screen variables
ui_Home_Page= NULL;
ui_Panel1= NULL;
ui_Title= NULL;
ui_LiveData= NULL;
ui_HistoricData= NULL;
ui_LiveDataLabel= NULL;
ui_HistoricDataLabel= NULL;
ui_Label5= NULL;
ui_Image7= NULL;

}
