// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HISTORIC_DATA_H
#define UI_HISTORIC_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Historic_Data
extern void ui_Historic_Data_screen_init(void);
extern void ui_Historic_Data_screen_destroy(void);
extern lv_obj_t *ui_Historic_Data;
extern void ui_event_HomeButton2( lv_event_t * e);
extern lv_obj_t *ui_HomeButton2;
extern lv_obj_t *ui_HOME2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_UNDER_CONSTRUCTION;
extern lv_obj_t *ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

