// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_PAGE_H
#define UI_HOME_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home_Page
extern void ui_Home_Page_screen_init(void);
extern void ui_Home_Page_screen_destroy(void);
extern lv_obj_t *ui_Home_Page;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Title;
extern void ui_event_LiveData( lv_event_t * e);
extern lv_obj_t *ui_LiveData;
extern void ui_event_HistoricData( lv_event_t * e);
extern lv_obj_t *ui_HistoricData;
extern lv_obj_t *ui_LiveDataLabel;
extern lv_obj_t *ui_HistoricDataLabel;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Image7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

