// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LIVE_DATA_H
#define UI_LIVE_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Live_Data
extern void ui_Live_Data_screen_init(void);
extern void ui_Live_Data_screen_destroy(void);
extern lv_obj_t *ui_Live_Data;
extern void ui_event_HomeButton3( lv_event_t * e);
extern lv_obj_t *ui_HomeButton3;
extern lv_obj_t *ui_HOME3;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_heatmap;
extern lv_obj_t *ui_legend;
extern lv_obj_t *ui_max;
extern lv_obj_t *ui_min;
extern void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label21;
extern lv_obj_t *ui_xAxis;
extern lv_obj_t *ui_yAxis;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

