// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Live_Data_Overview = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_Image8 = NULL;lv_obj_t *ui_HomeButton1 = NULL;lv_obj_t *ui_HOME1 = NULL;lv_obj_t *ui_Panel4 = NULL;lv_obj_t *ui_legend2 = NULL;lv_obj_t *ui_max2 = NULL;lv_obj_t *ui_min2 = NULL;lv_obj_t *ui_zoneGrid = NULL;lv_obj_t *ui_Z12 = NULL;lv_obj_t *ui_Label20 = NULL;lv_obj_t *ui_Z11 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Z10 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Z09 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Z08 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Z07 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Z06 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Z05 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Z04 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_Z03 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Z02 = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_Z01 = NULL;lv_obj_t *ui_Label12 = NULL;
// event funtions
void ui_event_HomeButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_Z12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_896003668);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1485633761);
}
}

void ui_event_Z11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1845464892);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1485633761);
}
}

void ui_event_Z10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_988524616);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1485633761);
}
}

void ui_event_Z09( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1401728645);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1485633761);
}
}

void ui_event_Z08( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_896003668);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1671086701);
}
}

void ui_event_Z07( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1845464892);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1671086701);
}
}

void ui_event_Z06( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_988524616);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1671086701);
}
}

void ui_event_Z05( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1401728645);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1671086701);
}
}

void ui_event_Z04( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_896003668);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1953993994);
}
}

void ui_event_Z03( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1845464892);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1953993994);
}
}

void ui_event_Z02( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_988524616);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1953993994);
}
}

void ui_event_Z01( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Live_Data_screen_init);
      _ui_image_set_property(ui_xAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1401728645);
      _ui_image_set_property(ui_yAxis, _UI_IMAGE_PROPERTY_IMAGE,& ui_img_1953993994);
}
}

// build funtions

void ui_Live_Data_Overview_screen_init(void)
{
ui_Live_Data_Overview = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Live_Data_Overview, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Live_Data_Overview, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Live_Data_Overview, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
ui_object_set_themeable_style_property(ui_Live_Data_Overview, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
ui_object_set_themeable_style_property(ui_Live_Data_Overview, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
lv_obj_set_style_border_width(ui_Live_Data_Overview, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_img_create(ui_Live_Data_Overview);
lv_img_set_src(ui_Image6, &ui_img_690597470);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image6, -3 );
lv_obj_set_y( ui_Image6, 399 );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8 = lv_img_create(ui_Live_Data_Overview);
lv_img_set_src(ui_Image8, &ui_img_livedataiconsmall_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image8, -365 );
lv_obj_set_y( ui_Image8, -205 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeButton1 = lv_btn_create(ui_Live_Data_Overview);
lv_obj_set_width( ui_HomeButton1, 56);
lv_obj_set_height( ui_HomeButton1, 30);
lv_obj_set_x( ui_HomeButton1, -307 );
lv_obj_set_y( ui_HomeButton1, -206 );
lv_obj_set_align( ui_HomeButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_HomeButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_HomeButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
ui_object_set_themeable_style_property(ui_HomeButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
ui_object_set_themeable_style_property(ui_HomeButton1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
lv_obj_set_style_border_width(ui_HomeButton1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_HomeButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HomeButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_HomeButton1, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_HomeButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_HomeButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_HomeButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_HomeButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HomeButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HOME1 = lv_label_create(ui_HomeButton1);
lv_obj_set_width( ui_HOME1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HOME1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HOME1, LV_ALIGN_CENTER );
lv_label_set_text(ui_HOME1,"HOME");
lv_obj_set_style_text_font(ui_HOME1, &ui_font_Futura_Book, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Live_Data_Overview);
lv_obj_set_width( ui_Panel4, 624);
lv_obj_set_height( ui_Panel4, 444);
lv_obj_set_x( ui_Panel4, 69 );
lv_obj_set_y( ui_Panel4, -3 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Border);
ui_object_set_themeable_style_property(ui_Panel4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Border);

ui_legend2 = lv_obj_create(ui_Live_Data_Overview);
lv_obj_remove_style_all(ui_legend2);
lv_obj_set_width( ui_legend2, 22);
lv_obj_set_height( ui_legend2, 399);
lv_obj_set_x( ui_legend2, 736 );
lv_obj_set_y( ui_legend2, 26 );
lv_obj_clear_flag( ui_legend2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_legend2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_legend2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_legend2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_legend2, lv_color_hex(0x1300FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_legend2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_legend2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_legend2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_max2 = lv_label_create(ui_Live_Data_Overview);
lv_obj_set_width( ui_max2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_max2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_max2, 730 );
lv_obj_set_y( ui_max2, 12 );
lv_label_set_text(ui_max2,"4095");
lv_obj_set_style_text_font(ui_max2, &ui_font_Futura_Book, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_min2 = lv_label_create(ui_Live_Data_Overview);
lv_obj_set_width( ui_min2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_min2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_min2, 742 );
lv_obj_set_y( ui_min2, 426 );
lv_label_set_text(ui_min2,"0");
lv_obj_set_style_text_font(ui_min2, &ui_font_Futura_Book, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_zoneGrid = lv_obj_create(ui_Live_Data_Overview);
lv_obj_remove_style_all(ui_zoneGrid);
lv_obj_set_width( ui_zoneGrid, 567);
lv_obj_set_height( ui_zoneGrid, 425);
lv_obj_set_x( ui_zoneGrid, 157 );
lv_obj_set_y( ui_zoneGrid, 15 );
lv_obj_set_flex_flow(ui_zoneGrid,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_zoneGrid, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( ui_zoneGrid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_zoneGrid, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Border);
ui_object_set_themeable_style_property(ui_zoneGrid, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Border);

ui_Z12 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z12, lv_pct(25));
lv_obj_set_height( ui_Z12, lv_pct(33));
lv_obj_set_align( ui_Z12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_Z12);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"ZONE 12");
lv_obj_set_style_text_font(ui_Label20, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z11 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z11, lv_pct(25));
lv_obj_set_height( ui_Z11, lv_pct(33));
lv_obj_set_align( ui_Z11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Z11);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"ZONE 11");
lv_obj_set_style_text_font(ui_Label1, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z10 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z10, lv_pct(25));
lv_obj_set_height( ui_Z10, lv_pct(33));
lv_obj_set_align( ui_Z10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Z10);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"ZONE 10");
lv_obj_set_style_text_font(ui_Label2, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z09 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z09, lv_pct(25));
lv_obj_set_height( ui_Z09, lv_pct(33));
lv_obj_set_align( ui_Z09, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z09, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z09, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z09, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Z09);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"ZONE 09");
lv_obj_set_style_text_font(ui_Label3, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z08 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z08, lv_pct(25));
lv_obj_set_height( ui_Z08, lv_pct(33));
lv_obj_set_align( ui_Z08, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z08, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z08, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z08, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Z08);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"ZONE 08");
lv_obj_set_style_text_font(ui_Label4, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z07 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z07, lv_pct(25));
lv_obj_set_height( ui_Z07, lv_pct(33));
lv_obj_set_align( ui_Z07, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z07, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z07, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z07, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Z07);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"ZONE 07");
lv_obj_set_style_text_font(ui_Label6, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z06 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z06, lv_pct(25));
lv_obj_set_height( ui_Z06, lv_pct(33));
lv_obj_set_align( ui_Z06, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z06, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z06, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z06, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Z06);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"ZONE 06");
lv_obj_set_style_text_font(ui_Label7, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z05 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z05, lv_pct(25));
lv_obj_set_height( ui_Z05, lv_pct(33));
lv_obj_set_align( ui_Z05, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z05, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z05, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z05, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Z05);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"ZONE 05");
lv_obj_set_style_text_font(ui_Label8, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z04 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z04, lv_pct(25));
lv_obj_set_height( ui_Z04, lv_pct(33));
lv_obj_set_align( ui_Z04, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z04, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z04, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z04, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Z04);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"ZONE 04");
lv_obj_set_style_text_font(ui_Label9, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z03 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z03, lv_pct(25));
lv_obj_set_height( ui_Z03, lv_pct(33));
lv_obj_set_align( ui_Z03, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z03, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z03, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z03, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Z03);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"ZONE 03");
lv_obj_set_style_text_font(ui_Label10, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z02 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z02, lv_pct(25));
lv_obj_set_height( ui_Z02, lv_pct(33));
lv_obj_set_align( ui_Z02, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z02, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z02, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z02, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Z02);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"ZONE 02");
lv_obj_set_style_text_font(ui_Label11, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Z01 = lv_btn_create(ui_zoneGrid);
lv_obj_set_width( ui_Z01, lv_pct(25));
lv_obj_set_height( ui_Z01, lv_pct(33));
lv_obj_set_align( ui_Z01, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Z01, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Z01, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Z01, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Z01);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"ZONE 01");
lv_obj_set_style_text_font(ui_Label12, &ui_font_Futura_Book_26, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_HomeButton1, ui_event_HomeButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z12, ui_event_Z12, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z11, ui_event_Z11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z10, ui_event_Z10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z09, ui_event_Z09, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z08, ui_event_Z08, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z07, ui_event_Z07, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z06, ui_event_Z06, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z05, ui_event_Z05, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z04, ui_event_Z04, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z03, ui_event_Z03, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z02, ui_event_Z02, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Z01, ui_event_Z01, LV_EVENT_ALL, NULL);

}

void ui_Live_Data_Overview_screen_destroy(void)
{
   if (ui_Live_Data_Overview) lv_obj_del(ui_Live_Data_Overview);

// NULL screen variables
ui_Live_Data_Overview= NULL;
ui_Image6= NULL;
ui_Image8= NULL;
ui_HomeButton1= NULL;
ui_HOME1= NULL;
ui_Panel4= NULL;
ui_legend2= NULL;
ui_max2= NULL;
ui_min2= NULL;
ui_zoneGrid= NULL;
ui_Z12= NULL;
ui_Label20= NULL;
ui_Z11= NULL;
ui_Label1= NULL;
ui_Z10= NULL;
ui_Label2= NULL;
ui_Z09= NULL;
ui_Label3= NULL;
ui_Z08= NULL;
ui_Label4= NULL;
ui_Z07= NULL;
ui_Label6= NULL;
ui_Z06= NULL;
ui_Label7= NULL;
ui_Z05= NULL;
ui_Label8= NULL;
ui_Z04= NULL;
ui_Label9= NULL;
ui_Z03= NULL;
ui_Label10= NULL;
ui_Z02= NULL;
ui_Label11= NULL;
ui_Z01= NULL;
ui_Label12= NULL;

}
