// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LIVE_DATA_OVERVIEW_H
#define UI_LIVE_DATA_OVERVIEW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Live_Data_Overview
extern void ui_Live_Data_Overview_screen_init(void);
extern void ui_Live_Data_Overview_screen_destroy(void);
extern lv_obj_t *ui_Live_Data_Overview;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Image8;
extern void ui_event_HomeButton1( lv_event_t * e);
extern lv_obj_t *ui_HomeButton1;
extern lv_obj_t *ui_HOME1;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_legend2;
extern lv_obj_t *ui_max2;
extern lv_obj_t *ui_min2;
extern lv_obj_t *ui_zoneGrid;
extern void ui_event_Z12( lv_event_t * e);
extern lv_obj_t *ui_Z12;
extern lv_obj_t *ui_Label20;
extern void ui_event_Z11( lv_event_t * e);
extern lv_obj_t *ui_Z11;
extern lv_obj_t *ui_Label1;
extern void ui_event_Z10( lv_event_t * e);
extern lv_obj_t *ui_Z10;
extern lv_obj_t *ui_Label2;
extern void ui_event_Z09( lv_event_t * e);
extern lv_obj_t *ui_Z09;
extern lv_obj_t *ui_Label3;
extern void ui_event_Z08( lv_event_t * e);
extern lv_obj_t *ui_Z08;
extern lv_obj_t *ui_Label4;
extern void ui_event_Z07( lv_event_t * e);
extern lv_obj_t *ui_Z07;
extern lv_obj_t *ui_Label6;
extern void ui_event_Z06( lv_event_t * e);
extern lv_obj_t *ui_Z06;
extern lv_obj_t *ui_Label7;
extern void ui_event_Z05( lv_event_t * e);
extern lv_obj_t *ui_Z05;
extern lv_obj_t *ui_Label8;
extern void ui_event_Z04( lv_event_t * e);
extern lv_obj_t *ui_Z04;
extern lv_obj_t *ui_Label9;
extern void ui_event_Z03( lv_event_t * e);
extern lv_obj_t *ui_Z03;
extern lv_obj_t *ui_Label10;
extern void ui_event_Z02( lv_event_t * e);
extern lv_obj_t *ui_Z02;
extern lv_obj_t *ui_Label11;
extern void ui_event_Z01( lv_event_t * e);
extern lv_obj_t *ui_Z01;
extern lv_obj_t *ui_Label12;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

