// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Live_Data = NULL;lv_obj_t *ui_HomeButton3 = NULL;lv_obj_t *ui_HOME3 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_heatmap = NULL;lv_obj_t *ui_legend = NULL;lv_obj_t *ui_max = NULL;lv_obj_t *ui_min = NULL;lv_obj_t *ui_Button7 = NULL;lv_obj_t *ui_Label21 = NULL;lv_obj_t *ui_xAxis = NULL;lv_obj_t *ui_yAxis = NULL;
// event funtions
void ui_event_HomeButton3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Page, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Home_Page_screen_init);
}
}

void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Live_Data_Overview, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Live_Data_Overview_screen_init);
}
}

// build funtions

void ui_Live_Data_screen_init(void)
{
ui_Live_Data = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Live_Data, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Live_Data, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Live_Data, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
ui_object_set_themeable_style_property(ui_Live_Data, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
ui_object_set_themeable_style_property(ui_Live_Data, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
lv_obj_set_style_border_width(ui_Live_Data, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeButton3 = lv_btn_create(ui_Live_Data);
lv_obj_set_width( ui_HomeButton3, 56);
lv_obj_set_height( ui_HomeButton3, 30);
lv_obj_set_x( ui_HomeButton3, -307 );
lv_obj_set_y( ui_HomeButton3, -206 );
lv_obj_set_align( ui_HomeButton3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HomeButton3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_HomeButton3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_HomeButton3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
ui_object_set_themeable_style_property(ui_HomeButton3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
ui_object_set_themeable_style_property(ui_HomeButton3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
lv_obj_set_style_border_width(ui_HomeButton3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_HomeButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HomeButton3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_HomeButton3, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_HomeButton3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_HomeButton3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_HomeButton3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_HomeButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HomeButton3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HOME3 = lv_label_create(ui_HomeButton3);
lv_obj_set_width( ui_HOME3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HOME3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HOME3, LV_ALIGN_CENTER );
lv_label_set_text(ui_HOME3,"HOME");
lv_obj_set_style_text_font(ui_HOME3, &ui_font_Futura_Book, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Live_Data);
lv_img_set_src(ui_Image2, &ui_img_livedataiconsmall_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, -365 );
lv_obj_set_y( ui_Image2, -205 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image5 = lv_img_create(ui_Live_Data);
lv_img_set_src(ui_Image5, &ui_img_690597470);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image5, -3 );
lv_obj_set_y( ui_Image5, 399 );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_Live_Data);
lv_obj_set_width( ui_Panel2, 624);
lv_obj_set_height( ui_Panel2, 444);
lv_obj_set_x( ui_Panel2, 69 );
lv_obj_set_y( ui_Panel2, -3 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Border);
ui_object_set_themeable_style_property(ui_Panel2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Border);

ui_heatmap = lv_obj_create(ui_Live_Data);
lv_obj_remove_style_all(ui_heatmap);
lv_obj_set_width( ui_heatmap, 554);
lv_obj_set_height( ui_heatmap, 404);
lv_obj_set_x( ui_heatmap, 157 );
lv_obj_set_y( ui_heatmap, 20 );
lv_obj_clear_flag( ui_heatmap, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_heatmap, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_heatmap, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);

ui_legend = lv_obj_create(ui_Live_Data);
lv_obj_remove_style_all(ui_legend);
lv_obj_set_width( ui_legend, 22);
lv_obj_set_height( ui_legend, 399);
lv_obj_set_x( ui_legend, 736 );
lv_obj_set_y( ui_legend, 26 );
lv_obj_clear_flag( ui_legend, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_legend, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_legend, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_legend, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_legend, lv_color_hex(0x1300FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_legend, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_legend, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_legend, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_max = lv_label_create(ui_Live_Data);
lv_obj_set_width( ui_max, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_max, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_max, 730 );
lv_obj_set_y( ui_max, 12 );
lv_label_set_text(ui_max,"4095");
lv_obj_set_style_text_font(ui_max, &ui_font_Futura_Book, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_min = lv_label_create(ui_Live_Data);
lv_obj_set_width( ui_min, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_min, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_min, 742 );
lv_obj_set_y( ui_min, 426 );
lv_label_set_text(ui_min,"0");
lv_obj_set_style_text_font(ui_min, &ui_font_Futura_Book, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button7 = lv_btn_create(ui_Live_Data);
lv_obj_set_width( ui_Button7, 109);
lv_obj_set_height( ui_Button7, 36);
lv_obj_set_x( ui_Button7, 10 );
lv_obj_set_y( ui_Button7, 64 );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Button7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Background);
ui_object_set_themeable_style_property(ui_Button7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Background);
ui_object_set_themeable_style_property(ui_Button7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Border);
ui_object_set_themeable_style_property(ui_Button7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Border);
lv_obj_set_style_border_width(ui_Button7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Button7, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Button7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Button7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Button7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_Button7);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"ZONE SELECT");
lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label21, &ui_font_Futura_Book, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_xAxis = lv_img_create(ui_Live_Data);
lv_img_set_src(ui_xAxis, &ui_img_1401728645);
lv_obj_set_width( ui_xAxis, 554);
lv_obj_set_height( ui_xAxis, 12);
lv_obj_set_x( ui_xAxis, 157 );
lv_obj_set_y( ui_xAxis, 428 );
lv_obj_add_flag( ui_xAxis, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_xAxis, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_yAxis = lv_img_create(ui_Live_Data);
lv_img_set_src(ui_yAxis, &ui_img_1953993994);
lv_obj_set_width( ui_yAxis, 12);
lv_obj_set_height( ui_yAxis, 404);
lv_obj_set_x( ui_yAxis, 716 );
lv_obj_set_y( ui_yAxis, 20 );
lv_obj_add_flag( ui_yAxis, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_yAxis, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_HomeButton3, ui_event_HomeButton3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);

}

void ui_Live_Data_screen_destroy(void)
{
   if (ui_Live_Data) lv_obj_del(ui_Live_Data);

// NULL screen variables
ui_Live_Data= NULL;
ui_HomeButton3= NULL;
ui_HOME3= NULL;
ui_Image2= NULL;
ui_Image5= NULL;
ui_Panel2= NULL;
ui_heatmap= NULL;
ui_legend= NULL;
ui_max= NULL;
ui_min= NULL;
ui_Button7= NULL;
ui_Label21= NULL;
ui_xAxis= NULL;
ui_yAxis= NULL;

}
